name: Pull Request Build Check Workflow

on:
  pull_request:
    branches:
      - development
      - main
    paths:
      - "**/*.js"
      - "**/*.jsx"
      - "**/*.ts"
      - "**/*.tsx"
      - "**/*.json"
      - "**/*.css"
      - "**/*.scss"

jobs:
  build-and-install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: risk-website/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('risk-website/**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          cd risk-website  # Change to the website directory
          npm install  # Or `yarn install` if you're using Yarn

      - name: Run Husky install
        run: |
          cd ..  # Go back to the root directory (WC3-Risk-Website)
          GIT_DIR=$(pwd)/.git husky install  # Set GIT_DIR to the root .git directory

      - name: Build the app
        run: |
          cd risk-website  # Change to the website directory
          npm run build  # Or your preferred build command (e.g., `yarn build`)
